create table if not exists public.payment_events (
  id bigint generated by default as identity primary key,
  transaction_id text not null unique,
  event_name text not null,
  processed_at timestamptz not null default now()
);

alter table public.payment_events enable row level security;